### ISSUE TITLE
Switch import in src/App.js from react-router-dom

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/radio-logger#14]
Need to refactor App.js to use the new v6 of react-router-dom

New version of 'react-router-dom' no longer uses Switch import

Fresh install of this repository causes this error when running CRA dev server with 'npm start'

**Comment by gbowne1** [comment]
Note this will cause a:

```Failed to compile.

./src/App.js
Attempted import error: 'Switch' is not exported from 'react-router-dom'.```

**Comment by Niklas-dev** [comment]
The routing is already switched to v6.

**Comment by gbowne1** [comment]
Yes this was fixed. Closing this issue.
