### ISSUE TITLE
Fix broken render caused by react-router-dom

### ISSUE THREAD

**Issue by ovadiaE** [gbowne1/radio-logger#29]
Current usage of React-Router-Dom causes blank render of the entire app

**Comment by gbowne1** [comment]
[Note] react-router and react-router-dom's documentation is [here](https://reactrouter.com/).

I believe our problem lies in src/App.js line 16 to 31.

The only render you'll get currently is the Nav.  

I was unaware that the new method for v6 of react-router-dom did not appear to be backward compatible with 5 on the surface of the issue, as had to change the folder name to element(s) from component(s).

**Comment by gbowne1** [comment]
This issue was fixed in a recent merge.  Closing this issue.
